services:
  front:
    image: node:23-bookworm-slim
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./front/vue:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "5173:5173"

  back:
    build:
      dockerfile: ./back/Dockerfile
      context: .
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./back:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    links:
      - mysql-db

  mysql-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fourbito
    volumes:
      - mysql-volum:/var/lib/mysql:rw
      - ./back/data/create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql-db
    depends_on:
      - mysql-db

volumes:
  mysql-volum:
