services:
  front:
    image: node:23-bullseye
    container_name: front
    build:
      context: ./front/vue
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./front/vue:/app
      - /app/node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - back

  back:
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/app
      - /app/node_modules:/app/node_modules
    working_dir: /app
    ports:
      - "3020:3020"
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - ./db:/var/lib/mysql
      - ./db/mysql/bd.sql:/docker-entrypoint-initdb.d/bd.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
